### ISSUE TITLE
Question: Sharing prometheus operator

### ISSUE THREAD

**Issue by ralberto** [coreos/prometheus-operator#1019]
<I'm not sure if there is a better place to raise questions like this, but couldn't find anywhere - feel free to redirect>

I'm deploying a kubernetes cluster that will be used by multiples teams, each one having a separate namespace. Each namespace has a user with the admin role (not cluster_admin), that is responsible of managing the namespace. 
I'd like to grant privileges to the namespace admin to deploy prometheuses, alertmanagers, servicemonitor, etc... resources... in their own namesapce.

Question: Do we need one prometheus operator in each namesapce, or one single operator can operate multiple prometheus in different namesapces? 

Thanks.

**Comment by ralberto** [comment]
Answering my own question:
One single prometheus operator handles all prometheus instances, etc....

**Comment by brancz** [comment]
Yes and that's what we recommend for users :slightly_smiling_face: .

**Comment by RickS-C137** [comment]
I know this issue is closed, but I just stumbled accross this and I'm having a kind of similar environment. We are deploying via the Helm chart. The problem is, I don't get which keys to use in the values.yaml to tell the operator to create a prometheus for multiple namespaces. I guess I can define a label somewhere in which namespaces a prometheus should be created.
So we have severel customers and each has multiple namespaces. For every customer we want to create a "monitoring namespace" which holds the Prometheus. The other namespaces have a servicemonitor which are scraped by the Prometheus. So how do I deploy this configuration?
