### ISSUE TITLE
Deploy Grafana & Grafana-watcher

### ISSUE THREAD

**Issue by shamalco** [coreos/prometheus-operator#1025]
Hi,

I successfully deployed prometheus-operator, and enable cluster monitoring. But I completely confused regarding the deployment of Grafana, there is no clear docmentation. I see in kube-prometheus there is a  [mainfest folder](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/grafana) called grafana, do I use this to deploy grafana? Or I need to deploy also [grafana-watcher](https://github.com/coreos/prometheus-operator/tree/master/contrib/grafana-watcher)? Or I should use only grafana watcher. I am bit confused what is the correct flow?

**Comment by ScottBrenner** [comment]
> [kube-prometheus combines the Prometheus Operator with a collection of manifests to help getting started with monitoring Kubernetes itself and applications running on top of it.](https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus)

To my knowledge a prometheus-operator does not include Grafana out-of-the-box, you'll have to set it up yourself. kube-prometheus automatically deploys and configures Grafana for you.

**Comment by shamalco** [comment]
I know that kube-prometheus has the manifest, but I am confused by the role grafana-watcher. I noticed there is a grafana-creditantials defined in kube-prometheus but not use by any of the manifests, but there is a tag-line "Grafana Watcher". Do I need to supplemental grafana with grafana watcher ?

**Comment by brancz** [comment]
I apologize for this, we're in the process of phasing out the grafana-watcher, as the functionality that it implements has inspired features that have as of Grafana v5 been implemented in Grafana directly. As a result we have the grafana-watcher still in this repo until a final version of Grafana v5 is released.

More broadly though, a lot of content in kube-prometheus is generated, including the Grafana manifest. This is the case, as Grafana dashboards can get very large, and may exceed the size limit of 1mb of a ConfigMap, which is why a member of the community implemented a bin-packer for Grafana dashboards into ConfigMaps, which however in turn means, that if a number of ConfigMaps are generated, they all need to be mounted, this is what the `contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator` exists for. Within it there are templates, where you find the actual template the final Grafana manifest.

Furthermore, as writing Grafana dashboards by hand is a big hassle, we started using a Python library to do so which, however is now unfortunately unmaintained.

Please note, that yes some of this is a bit hacky, and we are in the process of converting all this mess into a single unified language with jsonnet. This space should gradually become more clear as 1) Grafana v5 stable is released 2) we have finished our work to convert all existing things to jsonnet.

Please let me know if something is still unclear! :slightly_smiling_face:

**Comment by shamalco** [comment]
@brancz Thanks its crystal clear, I thought the same but I was just confused. Thanks for the support and excellent project, and made its much easier to setup prometheus and maintain it.

**Comment by suveerrao** [comment]
> I apologize for this, we're in the process of phasing out the grafana-watcher, as the functionality that it implements has inspired features that have as of Grafana v5 been implemented in Grafana directly. As a result we have the grafana-watcher still in this repo until a final version of Grafana v5 is released.
> 
> More broadly though, a lot of content in kube-prometheus is generated, including the Grafana manifest. This is the case, as Grafana dashboards can get very large, and may exceed the size limit of 1mb of a ConfigMap, which is why a member of the community implemented a bin-packer for Grafana dashboards into ConfigMaps, which however in turn means, that if a number of ConfigMaps are generated, they all need to be mounted, this is what the `contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator` exists for. Within it there are templates, where you find the actual template the final Grafana manifest.
> 
> Furthermore, as writing Grafana dashboards by hand is a big hassle, we started using a Python library to do so which, however is now unfortunately unmaintained.
> 
> Please note, that yes some of this is a bit hacky, and we are in the process of converting all this mess into a single unified language with jsonnet. This space should gradually become more clear as 1) Grafana v5 stable is released 2) we have finished our work to convert all existing things to jsonnet.
> 
> Please let me know if something is still unclear! 🙂

Thanks for your great work. Much appreciated. But seems like below mentioned path is currently unavailable. 

we are having some custom dashboards which we are unable to manage via configmap because of size limit constraints. kindly suggest us a soultion. 

> contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator
