### ISSUE TITLE
Support Alertmanager move to kingping

### ISSUE THREAD

**Issue by ledor473** [coreos/prometheus-operator#1064]
**What did you do?**
Tried to upgrade to Alertmanager >= v0.13.0

**What did you expect to see?**
A working Alertmanager

**What did you see instead? Under which circumstances?**
Pod stuck in CrashLoopBackOff

----

I've traced down the problem to this change: https://github.com/prometheus/alertmanager/pull/974

Since the format of the command line arguments changed, this logic should be changed: https://github.com/coreos/prometheus-operator/blob/dedb1f41e6c9229af05b88e16dc6cced39e2f0d6/pkg/alertmanager/statefulset.go#L174-L179

**Comment by brancz** [comment]
Which version of the Prometheus Operator are you using? This should be [fixed in `v0.16.1`](https://github.com/coreos/prometheus-operator/releases/tag/v0.16.1).

As the flags themselves are actually the same we just add an additional dash for Alertmanager `v0.13.0` and higher:

https://github.com/coreos/prometheus-operator/blob/e88fda4c182e26218bdd365e565b7a4cdd16ea5e/pkg/alertmanager/statefulset.go#L243-L247

**Comment by ledor473** [comment]
I completely missed that when looking at the code. We must be running an older version.

I'll close the issue right away as I'm confident it will work once upgraded 👍 

Thanks @brancz
