### ISSUE TITLE
Add static_configs to ServiceMonitor

### ISSUE THREAD

**Issue by metalmatze** [coreos/prometheus-operator#1086]
**What did you do?**
I'd like to use the combination of ServiceMonitors and static configuration for Federation.

**Use Case**: I want to run a Prometheus that scrapes a bunch of exporters and other apps via ServiceMonitors, but at the same time scrape other Prometheus via Federation with an URL like this: https://prometheus.example.com/federate

**What did you expect to see?**
I expected there to be a static_configs key on the ServiceMonitor's endpoint:
https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation
https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L302-L328

or

I'd like be able to merge a static config with the generated configuration from the operator.

**What did you see instead? Under which circumstances?**
There's currently no way to use Federation for static endpoints.

**Comment by brancz** [comment]
I think this is reasonable, in turn this incidentally also solves #1091 for most cases I imagine.

**Comment by mikeln** [comment]
Would definitely like to see

> I'd like be able to merge a static config with the generated configuration from the operator.

**Comment by ReillyProcentive** [comment]
Could we reconsider adding this back in? While `additionalConfigs` works for some use cases it doesn't cover the case where you want to have self-service monitoring of external targets (with only `additionalConfigs` you would need to allow those users to either directly modify the secret or have an operator that aggregates such rules into the secret). Having direct support for them in `ServiceMonitor` seems the best solution to me and most in line with the k8s philosophy.

**Comment by brancz** [comment]
The reason we don't have something like this, is because it doesn't allow enforcing labelling to create an authorization story. I'm not generally against your suggestion @ReillyProcentive, but I think that part needs to be thought through and it should probably be a separate object type, not the `ServiceMonitor` object.

**Comment by ReillyBrogan** [comment]
True, the name of `ServiceMonitor` does imply that it is for monitoring services. Would the next step potentially be a proposal for something like `ExternalTargetMonitor`?

**Comment by ReillyProcentive** [comment]
True, the name of `ServiceMonitor` does imply that it is for monitoring services. Would the next step potentially be a proposal for something like `ExternalTargetMonitor`?

**Comment by brancz** [comment]
This is pretty much plain Prometheus config, I wonder if that needs a CRD at all, or if it could just be a plain secret/configmap.

**Comment by brancz** [comment]
The downside to that is that a status block wouldn't really be possible.

**Comment by paivagustavo** [comment]
@brancz is there a issue where we can track this down? 

I've a prometheus setup on a namespace that not every developer on my cluster have access and currently developers can't add scrape jobs outside of our k8s cluster because it would require to change the prometheus deployment so they need to ask me to change the helm values file to add such jobs.
