### ISSUE TITLE
PodFrequentlyRestarting still active even though the container was removed

### ISSUE THREAD

**Issue by atopuzov** [coreos/prometheus-operator#1516]
**What did you do?**
Pod that was tripping `PodFrequentlyRestarting` alert got removed (there are no more metrics for `kube_pod_info` for the pod).

**What did you expect to see?**
Alert is not active anymore.

**What did you see instead? Under which circumstances?**
Alert was active for some time after the pod was non existent.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Kops cluster

* Manifests:

Kube state metrics used:
```
 gcr.io/google_containers/kube-state-metrics:v1.2.0
```

* Prometheus Operator Logs:

Not relevant to prometheus operator

* Example graph showing the event
<img width="1357" alt="issue" src="https://user-images.githubusercontent.com/202178/41777239-f7840af8-762a-11e8-84dc-326d1404d525.png">

`info` = `kube_pod_info{pod="POD"}`
`restarts` = `kube_pod_container_status_restarts_total{pod="POD"}`
`increase` = `increase(kube_pod_container_status_restarts_total{pod="POD"}[1h])` as used by the rule
`firing` = `ALERTS{alertname="PodFrequentlyRestarting",pod="POD",alertstate="firing"}`

ALERT definition (as provided by kube-prom)
```
alert: PodFrequentlyRestarting
expr: increase(kube_pod_container_status_restarts_total[1h])
  > 5
for: 10m
labels:
  severity: warning
annotations:
  description: Pod {{$labels.namespace}}/{{$labels.pod}} was restarted {{$value}}
    times within the last hour
  summary: Pod is restarting frequently

```

**Comment by hatemosphere** [comment]
+1, experiencing the same issue.

**Comment by brancz** [comment]
Thanks for opening this issue!

We should join the `kube_pod_info` metric onto the query, I believe then the alert should be instantly resolved as that metric won't exist anymore. Currently this happens, because the increase function's range query is 1 hour so it will look at the past hour of data, which is why the result set has data for up to 1 hour after the pod was deleted. As this alert is actually defined in this repository: [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin), we should take the discussion there. Would you mind opening the issue there @atopuzov?

**Comment by BenjaminHerbert** [comment]
@atopuzov Is there an issue for this topic?
@brancz Could you tell how the `kube_pod_info` metric can be joined into the query?

**Comment by atopuzov** [comment]
@BenjaminHerbert sorry I don't work with k8s anymore so I don't know.
