### ISSUE TITLE
How can I edit the alert manager configuration?

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1526]
**What did you do?**
Configuring prometheus.
**What did you expect to see?**
How can I edit the alertmanager configuration.
**What did you see instead? Under which circumstances?**
I have configured the alert-manager using your KB's. Now I need to add my custom config to the alertmanager. I know this is not a consulting channel,But if anyone can advice this, It will be a great help. I just need to know How can I set my customization to the  alertmanager yaml in this scenario.
**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Are you looking to discover an Alertmanager cluster within or outside of your Kubernetes cluster?

If it's within your cluster you should be able to configure everything via the Prometheus CRD, if there is anything missing, then we should add it.

If it's outside of the Kubernetes cluster, then you can use the `additionalAlertManagerConfigs` field of the Prometheus object to specify a Secret that contains a raw text Alertmanager discovery configuration.

> I know this is not a consulting channel

Sorry if it sounded to harsh in the past, that's not how I meant it. In this issue you more clearly asked a question we can answer, rather than sounding like commanding us to do something. :slightly_smiling_face:

**Comment by brancz** [comment]
Or are you talking about the actual configuration for Alertmanager? That's in a secret, and we describe [here](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#alertmanager-configuration) how it can be adapted.

**Comment by manuprometheus** [comment]
Thank you Brancz. This is want I actually looking for. sorry for the misunderstanding happens in my past query. I just need a suggestion from you about the alert manager and I got it now. Thank you :). Let me try this

**Comment by brancz** [comment]
Let us know how it goes! :slightly_smiling_face:

**Comment by manuprometheus** [comment]
Hi Brancz. Its worked perfectly. I have created secret for my own configuration and added it in the secret yaml. Now I am able to get alert on my slack. Thank a lot. :)

**Comment by brancz** [comment]
In that case I will close this issue here, but feel free to comment further or open a new issue if you run into any problems! (also if you think the documentation is not good enough, then we always highly highly appreciate pull requests from people with additional perspective than just ours! :slightly_smiling_face: )
