### ISSUE TITLE
Document clean-up steps for services and thirdpartyresources the operator creates

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#162]
The prometheus-operator conveniently self-creates some required services and third party resources on start-up. However, AFAIK, it lacks any automatic or manual mechanism to clean these up when it is deleted.

A problem this causes is that automated deployment of the operator, magically need to know these other resources are created in order to clean them up. Thus it would be in some ways better if these were instead a manually created manifest.

The automatic creation also increases the RBAC permissions the p-o requires. If these resources were created by the deployer, p-o could operate with fewer permissions.

I guess if we created a manifest and deployed it before p-o then p-o wouldn't try to recreate them? That might be a workaround for both issues?

Services:
- prometheus-operated
- alertmanager-operated

ThirdPartyResources
- prometheus.monitoring.coreos.com
- service-monitor.monitoring.coreos.com
- alertmanager.monitoring.coreos.com

**Comment by brancz** [comment]
The governing `Service`s are actually a requirement for the components to work properly with each other (for stable DNS identity) so they need to be controlled by the Prometheus Operator. It could however, clean up the governing `Service` from a namespace if there are no `Prometheus` or `Alertmanager` objects in that namespace anymore, but that will require as you said additional RBAC requirements, which is not inherently bad, just a fact.

In contrast, the `ThirtPartyResource`s need to be handled more delicately, as it takes the apiserver a bit until these are registered and so that would create a race condition when deploying the Prometheus Operator, which means we're not gaining anything when performing this "manually".

**Comment by whereisaaron** [comment]
Yeah, it's not a big deal either way. The operator is doing a great job creating and managing resources/config for the user, and generous RBAC permissions (in at least one namespace) are appropriate. It would be nice if it did as good a job cleaning up its resources. Even if that is just a manifest users can 'kubectl delete -f cleanup.yaml' after deleting the operator. So maybe no code changes, just a removal section in the README.md?

**Comment by whereisaaron** [comment]
@brancz if you agree it is useful to add, I wrote a starting point for README removal instructions in PR #165.

**Comment by brancz** [comment]
Closing here as #165 is merged :tada:
