### ISSUE TITLE
prometheus-config-reloader can't hit localhost

### ISSUE THREAD

**Issue by allen13** [coreos/prometheus-operator#1646]
**prometheus-config-reloader can't hit localhost**

For some strange reason just the prometheus-config-reloader pod resolves localhost to the wrong ip (not 127.0.0.1).  I assumed this was a problem with my underlying openshift cluster however the other two pods in the statefulset can reload the server just fine (I ran a curl from the prometheus pod). I manually changed the statefulset --reload-url to 127.0.0.1 and it worked. 

I realize that this issue is almost completely unfixable/untroubleshootable from the coreos developers side. My request is that the --reload-url either be made configurable or hard set to 127.0.0.1 . In the meantime I will compile prometheus-operator  myself. Maybe I will get lucky and find the underlying issue in the meantime.

Thanks!

* Image
```

quay.io/coreos/prometheus-config-reloader:v0.22.0

```

* Kubernetes cluster kind: 

	openshift enterprise 3.9.31

* Manifests:
prometheus stateful set generated from kind: Prometheus
```
 - args:
            - '--reload-url=http://localhost:9090/-/reload'
```

* Prometheus Operator Logs - prometheus-config-reloader:

```

ts=2018-07-19T16:55:15.411201193Z caller=main.go:35 msg="Starting prometheus-config-reloader version '0.22.0'."
  | level=info ts=2018-07-19T16:55:15.60978331Z caller=reloader.go:77 msg="started watching config file for changes" in=/etc/prometheus/config/prometheus.yaml out=/etc/prometheus/config_out/prometheus.env.yaml
  | level=error ts=2018-07-19T16:55:45.611089319Z caller=runutil.go:43 msg="function failed. Retrying" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload:  dial tcp 10.15.12.167:9090: i/o timeout"


```

**Comment by brancz** [comment]
The config reloader is mainly an implementation detail, ideally we wouldn't need to do a request at all, I hope that Kubernetes stabilizes sharing PID namespace, so that the reloader can just send a SIGHUP signal to the Prometheus process. So I don't think we should make this configurable in the Prometheus object, but given that we have seen these problems a number of times I think it's fair to have a flag on the Prometheus operator to configure this if people absolutely cannot find out what their problem is (it's probably DNS, it's always DNS). Such a flag would need to be declared experimental and may be removed at any time, ideally when sharing PID namespace becomes available.

**Comment by brancz** [comment]
That won't work in IPv6 only setups anymore. I realize that that's relatively scarce right now, but we've had reports of IPv6 only users (in other regards). I'd prefer not to drop compatibility with a set of users whose clusters are working correctly.

In the past we have heard that this is because the Kubernetes DNS soluteon has an entry for localhost. You should make sure that the first resolver is the local one and make sure your DNS addon is not doing this.

**Comment by allen13** [comment]
Thanks for the great feedback! I'll definitely put in a PR. How does this work for the flag?

```
flagset.StringVar(&cfg.LocalReloadHost, "local-reload-host", "localhost", "Experimental: Change the host used for the config reload url")
```

**Comment by mxinden** [comment]
Closing here as #1655 is merged. @allen13 thanks for the work.

**Comment by shayneoneill** [comment]
Is there a fix here for us users? I'm getting this error on 127.0.0.1
