### ISSUE TITLE
Get metrics from specific namespaces in a K8 cluster

### ISSUE THREAD

**Issue by debbiswal** [coreos/prometheus-operator#1651]
I have a K8 cluster having multiple namespaces.
For example : DEV,PPE,LNP,REDIS,monitoring  and default,kubesystem,kubepublic
I have , added a PV to Prometheus deployment with retention of 5 days.

By default , I am getting metrics from all the namespaces , which eating up the PV allocated space.

Is it possible to specify to get metrics from only PPE,REDIS,monitoring?

**Comment by brancz** [comment]
No component exists today to do this, however, there is something that we will build in order to do this, but it doesn't exist today. We do have some very early stage PoCs, so it's coming, but we're not there. Although related it will be solved outside of the Prometheus Operator repository. We will probably integrate what we build with the kube-prometheus stack (which we would like to extract out of this repository as well, but that will take some time to become a reality).

**Comment by debbiswal** [comment]
Thanks
