### ISSUE TITLE
kube-prometheus README missing a few steps?

### ISSUE THREAD

**Issue by KlavsKlavsen** [coreos/prometheus-operator#1728]
**What did you do?**
Tried to follow contrib/kube-prometheus/README.md
did:
$ mkdir my-kube-prometheus; cd my-kube-prometheus
$ jb init
$ jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus

And then cannot get any further :(

**What did you expect to see?**
guide to create config files in own git repo (as guide says is best) and how to compile to to customized config, that can be loaded into running cluster..

**What did you see instead? Under which circumstances?**
I cannot figure out how to run the "ksonnet" part - but text says its optional (and one should do the below jsonnet compile instead..
The jsonnet compile script however does this:
jsonnet -J vendor -m manifests "${1-example.jsonnet}"
which isn't in the "my-kube-prometheus" folder I just created - following the guide :(

I am hoping to f.ex. adjust grafana config - to require LDAP login (we have a local grafana running with this setup.. hoping to figure out how to merge that into "my kube-prometheus" config :)

**Comment by brancz** [comment]
Thanks a lot for opening this issue! We are aware that the documentation is lacking information, we're just too close to it to see what. We highly appreciate if you open issues for any obstacles you encounter that are not documented enough! :slightly_smiling_face: .

I just opened https://github.com/coreos/prometheus-operator/pull/1727, please let me know if after those changes things become more clear. We should definitely remove the "optional" wording, as for any customization jsonnet is required/recommended, the rendered manifests are only there in order to give people a preview of what they can get.

**Comment by KlavsKlavsen** [comment]
I added my questions to #1727 - as it does not cover the steps between jb install.. and getting to where I can add mixin's, customize grafana config etc. (ie. config section).
Thank you for responding - I will try to give you constructive feedback - and being new to kubernetes (just setup my cluster) - I am definetely in a position to know whats "missing" - from a K8 newbie's point of view ;)

**Comment by jolson490** [comment]
fyi @KlavsKlavsen , here's some info about setting up / enabling LDAP for grafana in kube-prometheus:
 * http://docs.grafana.org/installation/ldap/
 * https://github.com/coreos/prometheus-operator/issues/835#issuecomment-385063912

(I'm looking into / considering doing this, but haven't actually tried it yet.)
