### ISSUE TITLE
renderedRules with kube-prometheus not working

### ISSUE THREAD

**Issue by nroitero** [coreos/prometheus-operator#1795]
**What did you do?**
after downloading kube prometheus `jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus`
after running the build with prometheus-additional-rendered-rule-example.jsonnet and example.rules.yaml in the root

**What did you expect to see?**
 new rule to appear in generated file `manifest/prometheus-rules.yaml`

**What did you see instead? Under which circumstances?**
default rules only

**Environment**

* Prometheus Operator version:
irrelevant

* Kubernetes version information:
irrelevant

* Kubernetes cluster kind: 
irrelevant

**Comment by brancz** [comment]
Sorry for only getting to this now. Since introducing the `PrometheusRule` object, I think the best solution would be to convert the existing rules to json and treat them as jsonnet code, as we can't have jsonnet parse yaml (maybe jsonnet should be able to do that, but right now it can't: https://github.com/google/jsonnet/issues/460).

We should change the documentation to say that people need to convert their yaml rules to json and treat it as jsonnet code like [here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md#alerting-rules), and tell people they can just use `import` to import the external file that way.

Would you like to create a PR to change these docs? :slightly_smiling_face:

**Comment by matthoop** [comment]
Just come across this problem too.  so for now 
```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
  _config+:: {
    namespace: 'monitoring',
    prometheus+:: {
      renderedRules: {
        'example.rules.yaml': (importstr 'example.rules.yaml'),
      },
    },
  },
};
```
`renderedRules` with `importstr` still not working, right?

**Comment by brancz** [comment]
Rendered rules doesn't work anymore, since the PrometheusRule object was introduced, what you need to do is convert your existing rules to json and do a normal `import` treating the rules that are now json as jsonnet imported files.

**Comment by aviau** [comment]
If they are no longer supported, I suggest that rendered rules are removed from the documentation

**Comment by brancz** [comment]
Agreed.

**Comment by elbertwang** [comment]
@brancz is there any detail doc to introduce the procedure you mentioned? Thank you.
I am so confused about how to import the existing rule into prometheus...

**Comment by brancz** [comment]
@elbertwang I just opened https://github.com/coreos/prometheus-operator/pull/2447, hopefully that cleares it up :slightly_smiling_face:
