### ISSUE TITLE
confusion with metrics

### ISSUE THREAD

**Issue by navi86** [coreos/prometheus-operator#1840]
- expr: |
        count by (node) (sum by (node, cpu) (
          node_cpu{job="node-exporter"}
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
        ))
      record: node:node_num_cpu:sum
Could you help me to understand the idea of that calculation, according to name of metrics it's should just calculate count of cpu on the host or cpu usage, but I am not sure due to the fact that I have no data for that metric

P.S. I don't use prometheus operator but as far as I know this metric should be calculated without prometheus-opearator too.

**Comment by brancz** [comment]
This is likely due to labeling of your node exporter target not having the namespace and pod labels, and you also must be collecting kube-state-metrics’ metrics with “honor_labels: true”. We’ve been through all of this, which is why we provide our stack so we don’t have to all go through the same mistakes :)

As this is not as issue with the Prometheus operator I’m going to close this here.
