### ISSUE TITLE
rule file selector

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#194]
We will eventually hit the size limit of a single `ConfigMap` with alerting rules/recording rules therefore we need a mechanism to select multiple. I propose to instead of trying to mount a single `ConfigMap` to select `ConfigMap`s via a label selector.

This would be a breaking change to the current way we handle rule files.

Also cross referencing to #166, should we keep using `ConfigMap`s or use `Secret`s here as well. I would say Alertmanager and Prometheus configs should be `Secret`s but the rule files can remain to be `ConfigMap`s, but I'm happy to be convinced otherwise.

@fabxc 

/cc @whereisaaron

**Comment by whereisaaron** [comment]
All sounds good.

I don't know how big a rules collection might get (in number or size), but 'etcd' is I think not supposed to be bulk storage. If the collection could get very large, at some point you could instead have the option to configure a PV and path as the source for rules files, and mount that to provide the rules files rather than dozens of ConfigMaps. So you could decided to support one of:
- A single ConfigMap by name
- A label selector of ConfigMaps
- A PV and path (path within the in PV)

Like ConfigMaps, many types of PVs can be shared (a least read-only).

But maybe a selector of ConfigMaps is more that enough for most use cases.

**Comment by brancz** [comment]
Looking at current rule sets I think we won't even hit the limit of a single `ConfigMap` for a while. For cluster monitoring I'm expecting an absolute max get up to 3 `ConfigMap`s (current volume for etcd and kubernetes rules is ~150kb including a large set of recording rules).
