### ISSUE TITLE
Enable control over Prometheus options, especially memory use

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#203]
I am finding it challenging to get the Prometheus memory use to match the Kubernetes resource request.

Initially with the 200mi memory request actual memory use ran to ~800mi. I saw the suggestion was 2Gi, so I changed the memory request to 2Gi. Without any other changes memory use quickly increased to 8Gi.

I checked all the [memory use pressure issues](https://prometheus.io/docs/operating/storage/#memory-usage) in case they was back-log but none of that applied. So I was seeking to set memory chunk parameters, but I don't see a mechanism to pass arguments to the Prometheus instances?

While looking I found the like cause of my problems appears to be this formula below, that keeps increasing the Prometheus memory use each time the Kubernetes request is increased. It has a fixed factor of 5, however my experience suggests a factor of about 20 is appropriate - if you want Prometheus memory use to approximately match the Kubernetes resource request. (I am collecting most of the same metrics as kube-prometheus, except I changed the rate down from 15s to 60s).

Could something in the Prometheus TPR enable control over this factor, or the passing of arguments to Prometheus?

https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L156-L176
```
	// We attempt to specify decent storage tuning flags based on how much the
	// requested memory can fit. The user has to specify an appropriate buffering
	// in memory limits to catch increased memory usage during query bursts.
	// More info: https://prometheus.io/docs/operating/storage/.
	reqMem := p.Spec.Resources.Requests[v1.ResourceMemory]
	// 1024 byte is the fixed chunk size. With increasing number of chunks actually
	// in memory, overhead owed to their management, higher ingestion buffers, etc.
	// increases.
	// We are conservative for now an assume this to be 80% as the Kubernetes environment
	// generally has a very high time series churn.
	memChunks := reqMem.Value() / 1024 / 5

	promArgs := []string{
		"-storage.local.retention=" + p.Spec.Retention,
		"-storage.local.memory-chunks=" + fmt.Sprintf("%d", memChunks),
		"-storage.local.max-chunks-to-persist=" + fmt.Sprintf("%d", memChunks/2),
		"-storage.local.num-fingerprint-mutexes=4096",
		"-storage.local.path=/var/prometheus/data",
		"-config.file=/etc/prometheus/config/prometheus.yaml",
	}
```

**Comment by brancz** [comment]
Collecting metrics at a 60s interval is nothing unusual, 15s is rather often, from what I've seen most people tend to do 30s.

This is definitely one of the hardest parts of operating Prometheus. Luckily there is some work on the way by @beorn7 that from what I know is targeted as part of the Prometheus v1.6.0 release to be able to specify an upper bound for memory usage by Prometheus.

https://github.com/prometheus/prometheus/issues/455#issuecomment-284271138 

Furthermore @fabxc is currently reworking the entire storage layer, which is targeted for a Prometheus 2.0 release, that will make all memory behavior predictable in a way that Prometheus setups are much better planable.

@beorn7 and @fabxc can comment on those two topics a lot more elaborately.

In terms of work on the TPR I think we should hold off on implementing something targeting current latest (`v1.5.2`) and see what we can do with `v1.6.0` or even `v2.0`.

**Comment by beorn7** [comment]
The tweak I've been working on works surprisingly well, given that it is not really a fundamental solution. Note that it doesn't specify a strict upper bound of memory usage. It merely evicts cached memory chunks from memory if the heap approaches a target size. It also adjusts the persistence pressure so that more effort is invested in persisting chunks to avoid a situation where chunks needed to be evicted but none are evictable. Since memory management in Go is, as of now, black magic, the heap _may_ grow beyond the target size, and then all of that doesn't directly translate into the physically used memory (RSS), which might be quite close to the heap size but can also be much bigger. (I'm currently operating with a heap size target being two thirds of the available physical memory, which is fairly safe but not 100%.)

@fabxc 's new storage solves the original sin of the current storage design, which is loading data from files explicitly into memory before we act on it. Since we have millions of files on disk with the current storage design, we cannot just `mmap` them all. The new design avoids the file count explosion and can thus leverage `mmap`, i.e. most of that memory vs. disk trade-off is now done by the OS, which is really good in that and also the correct authority for it. The process memory is quite consistent in size and way smaller than with the current storage. Which doesn't mean Prometheus wouldn't need the additional memory for the page cache. If you give it less RAM, it will not OOM, though, but just degrade in performance (comparable to the OS starting to swap), which is much saner behavior than before. ( @fabxc to correct any of the above.)

**Comment by fabxc** [comment]
All accurate.

@beorn7 have you tested your change with environments with high series churn? Those seem to break the formula we have been using so far pretty quickly. If it generally works well, I'd be really keen to cut a 1.6 release with that sooner than later.

**Comment by beorn7** [comment]
The "high series churn" scenario triggered my tweak in the first place. So: yes.

"High series churn" is the one of the two most frequent scenarios for OOM. Scenario: We set the memory chunks quite conservatively (like one memory chunk per 6kiB of RAM). That works nicely in most cases. But then a large-scale micro-service deploys three times in 30m (quite common in practice), and the time series on the corresponding Prometheus server quadruple. The memory chunk setting is high enough to still have more chunks than memory series, and the persistence pressure is low enough, so we can evict enough chunks to keep the number of memory chunks at the provided value. However, now the memory footprint per series is enough to make us OOM.

And BTW, the other OOM scenario is if a giant query pins more chunks than we can handle. That case won't be handled by the planned tweak as it can only evict evictable chunks. However, now that we have a notion of "memory pressure", we can add a query killer as a last resort before OOMing. Different story, though...

**Comment by sdurrheimer** [comment]
Prometheus 1.6 is finally out. It's time to make the prometheus-operator compatible with the new `-storage.local.target-heap-size` flag 🙌

**Comment by brancz** [comment]
Having the `target-heap-size` integration now with the latest release I think we've exhausted our possibilities to allow better control of memory use. Explicit access to the flags is as described in #306 is a non goal for us. Closing here.
