### ISSUE TITLE
Alert name is not specifying in the alert being received when more than one is triggered.

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2044]
**What did you do?**
Configured the alert for node memory usage.
**What did you expect to see?
The triggered alert should show the name of all nodes that are triggered.
**What did you see instead? Under which circumstances?**
Alerts are receiving with the node name when there is one node memory alert is triggered. But the name of node is not showing if more than one node memory alert is triggered.
**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
![alert](https://user-images.githubusercontent.com/40427565/47433211-939b0100-d7bd-11e8-9473-62cd5cdd11ec.png)

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I hope you understand it doesn't make sense for this repo to be an additional point to solve Prometheus problems, it makes sense to bundle them in one place :slightly_smiling_face: .
