### ISSUE TITLE
Grafana values.yaml not being processed

### ISSUE THREAD

**Issue by rewt** [coreos/prometheus-operator#2072]
**What did you do?**
 helm upgrade --install kube-prometheus coreos/kube-prometheus --namespace monitoring -f values.yaml

**What did you expect to see?**
operator installed with values specified in ./helm/grafana/values.yaml

**What did you see instead? Under which circumstances?**
operator installed correctly, without grafana updates to values.yaml

**Environment**
Azure Kubernetes Service

* Prometheus Operator version:
image: quay.io/coreos/prometheus-operator:v0.25.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Azure

**Comment by RiRa12621** [comment]
looks like you only passed in one set of values but if you want to have a second set of values you need to add the `-f` flag again and then your values.
for example:
```
helm upgrade --install kube-prometheus coreos/kube-prometheus --namespace monitoring -f values.yaml -f ./helm/grafana/values.yaml
```

**Comment by brancz** [comment]
The prometheus-operator and kube-prometheus helm charts have been migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests or issues about it in this repository. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

Please open an issue on the upstream helm charts repository, as the Prometheus Operator maintainers neither use nor maintain the helm charts.

Thank you for your understanding! :slightly_smiling_face:
