### ISSUE TITLE
Resource Prometheus can be created by Deployment?

### ISSUE THREAD

**Issue by aixeshunter** [coreos/prometheus-operator#2214]
**What did you do?**
I deployed a prometheus cluster by `prometheus-operator`, and the operator created `prometheus` 
 as statefulset.

The prometheus data 
```bash
# kubectl get sts -n kube-system
NAME                DESIRED   CURRENT   AGE
alertmanager-main   1         1         5d
prometheus-k8s       1         1         5d
```
And then, I poweroff the master node (I have  3 master nodes) that prometheus pod exists.

**What did you expect to see?**
The Prometheus pod will run in other master nodes.

**What did you see instead? Under which circumstances?**
```bash
[root@master1 ~]# kubectl get po -n kube-system -o wide | grep prom
prometheus-k8s-0                                       3/3       Unknown             7          5d        10.244.0.59    master2
```
The pod can not run on other node.

**Environment**

* Prometheus Operator version:

	v0.24.0

* Kubernetes version information:

```bash
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0", GitCommit:"3d2c54994840f73bd2ac99e505a3cad2c70e8161", GitTreeState:"clean", BuildDate:"2018-08-08T01:40:36Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0", GitCommit:"3d2c54994840f73bd2ac99e505a3cad2c70e8161", GitTreeState:"clean", BuildDate:"2018-10-18T20:21:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

```

Does prometheus operator create the prometheus by deployment instead of statefulset?
And I don't want to delete the `prometheus pod` mannually.

**Comment by s-urbaniak** [comment]
@aixeshunter prometheus operator will use statefulsets as prometheus is a stateful backend. If you power down the node and don't drain it, the k8s scheduler won't reschedule it on a different node, also see https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/.

**Comment by aixeshunter** [comment]
@s-urbaniak Thanks ! I have a question now: why prometheus operator not monitor prometheus pod status?
If operator can delete the prometheus pod with `Unknown` status automatically, is it better?

**Comment by s-urbaniak** [comment]
Monitoring the prometheus' pod status is in the responsibility domain of k8s, via the statefulset controller in the controller manager. The prometheus operator is supposed to only monitoring the statefulset status.

**Comment by aixeshunter** [comment]
@s-urbaniak 
I am sorry to ask you another question.
I found that alertmanager pod can be rescheduled in another node but prometheus not, and they were all controlled by `statefulset`.
```bash
[root@master1 prometheus-plugin]# kubectl get sts -n monitoring 
NAME                DESIRED   CURRENT   AGE
alertmanager-main   1         1         46d
prometheus-k8s      1         1         46d
```

before the power down:
```bash
alertmanager-main-0                    2/2       Running    0          1d       172.18.1.53    node1.hikcloud
prometheus-k8s-0                       3/3       Running    0           1d       172.18.2.19    node1.hikcloud
```

power down the `node1` and wait for 5m:
```bash
alertmanager-main-0                    2/2       Running    0          1m        172.18.2.32    master3.hikcloud
prometheus-k8s-0                       3/3       Unknown0           1d       172.18.2.19    node1.hikcloud
```

The `Alertmanager` resource yaml:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
  resourceVersion: "11969572"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/alertmanagers/main
  uid: d0ede83c-db34-11e8-966a-5254008abd3e
spec:
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: http://127.0.0.1:9093
  replicas: 1
  version: v0.15.2
```

The `Prometheus` resource yaml:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
  resourceVersion: "11998660"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/k8s
  uid: f05c4968-db34-11e8-966a-5254008abd3e
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  replicas: 1
  retention: 168h
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
        selector:
          matchLabels:
            app: prometheus-k8s
  version: v2.4.3
```

**Comment by s-urbaniak** [comment]
@aixeshunter there is no difference between the two, both are statefulsets. Please consider to iterate on the scheduling behavior of k8s with regard to statefulsets. The reason why alertmanager was rescheduled and prometheus can depend on the the specific situation in your cluster.

As per https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#delete-pods:

Kubernetes (versions 1.5 or newer) will not delete Pods just because a Node is unreachable. The Pods running on an unreachable Node enter the ‘Terminating’ or ‘Unknown’ state after a timeout. Pods may also enter these states when the user attempts graceful deletion of a Pod on an unreachable Node. The only ways in which a Pod in such a state can be removed from the apiserver are as follows:

- The Node object is deleted (either by you, or by the Node Controller).
- The kubelet on the unresponsive Node starts responding, kills the Pod and removes the entry from the apiserver.
- Force deletion of the Pod by the user.

The recommended best practice is to use the first or second approach. If a Node is confirmed to be dead (e.g. permanently disconnected from the network, powered down, etc), then delete the Node object. If the Node is suffering from a network partition, then try to resolve this or wait for it to resolve. When the partition heals, the kubelet will complete the deletion of the Pod and free up its name in the apiserver.

Normally, the system completes the deletion once the Pod is no longer running on a Node, or the Node is deleted by an administrator. You may override this by force deleting the Pod.

**Comment by pytimer** [comment]
Hi, i have the same issue.

I use `kubeadm` to create kubernetes cluster. Maybe operator handler alertmanager lifecycle? I don't know more about it.

Kubernetes version information:

```sh
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brancz** [comment]
We moved everything to use a parallel pod management policy in the statefulset, we've seen that to help with this behavior. Let us know if it helps you too. I'm closing this, here but if you are still seeing behavior that you feel is not appropriate, please feel free to create a new issue! :slightly_smiling_face:
