### ISSUE TITLE
Grafana roadmap

### ISSUE THREAD

**Issue by nirdothan** [coreos/prometheus-operator#224]
In reference to [#115](https://github.com/coreos/prometheus-operator/issues/115)
The current behavior of [grafana-watcher](https://github.com/coreos/prometheus-operator/blob/master/contrib/grafana-watcher) relies on a ConfigMap as the master dashboard repository. 
When you design a new dashboard in Grafana you need to manually export it and merge it into the ConfigMap manifest, which is quite tedious to do. Is there a plan to automate this process ?

In addition, while going through this process, I noticed that we were [using](https://github.com/coreos/prometheus-operator/blob/8dfc9d768ef9f7b31494e1dbb47e00dfcbfd6353/contrib/grafana-watcher/grafana/dashboard.go#L87) the Grafana `/api/dashboards/import` API, which seems to be undocumented in the[ Grafana API reference](http://docs.grafana.org/http_api/dashboard/). Why aren't we using the documented API?

**Comment by brancz** [comment]
The `[POST] /api/dashboards/db` endpoint was also undocumented at the time of implementing the grafana-watcher :slightly_smiling_face: . As far as I can tell they have the exact same functionality, so it should just be replaceable.

> Is there a plan to automate this process ?

Glad you ask, because it already is. It is part of [kube-prometheus](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus) and the scripts to do that can be found in [`hack/scripts`](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/scripts/). You are particularly looking for the `generate-dashboards-configmap.sh` script executed from the `generate-manifests.sh` script.

**Comment by brancz** [comment]
Now using the documented API and he workflow is already automated :)

**Comment by brancz** [comment]
It turns out, that the `/import` endpoint actually slightly differs, and does not allow templating, this didn't show in my tests, but in more complex dashboards it does appear. Will have to revert to the `/import` endpoint again.
