### ISSUE TITLE
How can I use Aws SNS and MS Team at the same time as both use webhook configs

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2282]
Below is my alertmanager.yaml

global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  receiver: forwarder
receivers:
- name: 'forwarder'
  webhook_configs:
  - send_resolved: true
    url: http://alertmanager-sns-forwarder-svc.monitoring:9087/alert/PB_SYSTEST_K8S_ALERTS
  webhook_configs:  
  - send_resolved: true
    url: 'http://prometheus-msteams.monitoring:9094/alertmanager' 

1st webhook is for AWS SNS and 2nd is for MS Team but I can't have two webhook_configs in alertmanager.yaml.

Any workaround for such use cases?

**Comment by brancz** [comment]
You need to use a separate name for the different receivers.

This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I hope that makes sense, therefore closing here :slightly_smiling_face:
