### ISSUE TITLE
Two image tags are incorrect

### ISSUE THREAD

**Issue by alanpeng** [coreos/prometheus-operator#2291]
**What did you do?**
unzip the source code tarball file and checked the image tag in those yaml files

**What did you expect to see?**
prometheus-operator-0.27.0/contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
in this file, I should see:
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.27.0
        image: quay.io/coreos/prometheus-operator:v0.27.0

**What did you see instead? Under which circumstances?**
but it was:
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.26.0
        image: quay.io/coreos/prometheus-operator:v0.26.0

**Environment**

* Prometheus Operator version:

	v0.27.0

**Comment by brancz** [comment]
kube-prometheus is a sub-project of the prometheus-operator, it is versioned separately (in fact as of right now, it is so fast moving that we have decided to not formally version it at all)

We do want to extract kube-prometheus into its own project where we will start versioning it appropriately.

I'll close this, as everything is as it is intended. I understand the confusion though, which is why we want to make more clear that they're two separate (only related) projects.
