### ISSUE TITLE
Targets kube-state-metrics and node-exporter could not be scraped

### ISSUE THREAD

**Issue by play-io** [coreos/prometheus-operator#2316]
**What did you do?**
```bash
git clone ...prometheus-operator
cd prometheus-operator/contrib/kube-prometheus
kubectl apply -f manifests/
```

**What did you expect to see?**
`Node-exporter` and `kube-state-metrics` are being scraped

**What did you see instead? Under which circumstances?**
> Get https://IP:PORT/metrics: dial tcp IP:PORT: connect: connection refused

**Environment**
n/a

* Prometheus Operator version:

	v0.27.0

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Managed at Digitalocean

* Manifests:
n/a

* rbac-proxy Logs:
No logs

* node-exporter and kube-state-metrics logs
processes are successfully started.
No errors

**Comment by metalmatze** [comment]
I've started a DigitalOcean managed Kubernetes cluster and can confirm that node-exporters and kube-state-metrics cannot be scraped. Looking into a fix. It's probably HTTPS related.

**Comment by complex64** [comment]
I'd like to propose adding this to the pod spec:

```yaml
readinessProbe:
  tcpSocket:
    port: 9100
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  tcpSocket:
    port: 9100
  initialDelaySeconds: 5
  periodSeconds: 10
```
What do you think?

**Comment by play-io** [comment]
> This seems to be related to [brancz/kube-rbac-proxy#26](https://github.com/brancz/kube-rbac-proxy/issues/26)
> We are working on a fix.
> In the meantime you can checkout `5f5d2316c8ee88d796b493676731b2d8846b0375` in this repository and use the manifests there. It's 99% the same.
> Sorry.

Thanks for the replies.

Question - you want me to test it or proposing work around? As work around i exposed node-exporter and kube-system-metrics on 0.0.0.0. For Node-exporter it also required to delete `hostNetwork: true` otherwise my second pod was not scrapped (or could not be started, do not remember).

**Comment by complex64** [comment]
> Is it working for "Quick Start" configuration, when node-exporter is listening only on `127.0.0.1`?
Fair point! I guess not

**Comment by MarkDeckert** [comment]
Is this due to the recently added --tls-cipher line in manifests?

524efc55c83f28f651e8c6f0dfae68b292dfa462 in node exporter and kube-state-metrics.

I started getting no metrics from either of these sources until I removed these lines.

**Comment by MarkDeckert** [comment]
According to this 3e7bb3da22597e0a2b7ed0a7b6e0f6a82796eb5c , the ciphers are explicitly specified now in order to disable known insecure ciphers.  This appears to break other components in the operator -- just prometheus perhaps?  I'm not getting any relevant results when I look at pod logs so not sure where to see the errors.

**Comment by brancz** [comment]
We're actively working on a fix for this, unfortunately it is more involved. We will make an announcement as soon as this is out the door.

**Comment by play-io** [comment]
> According to this [3e7bb3d](https://github.com/coreos/prometheus-operator/commit/3e7bb3da22597e0a2b7ed0a7b6e0f6a82796eb5c) , the ciphers are explicitly specified now in order to disable known insecure ciphers. This appears to break other components in the operator -- just prometheus perhaps? I'm not getting any relevant results when I look at pod logs so not sure where to see the errors.

I

**Comment by brancz** [comment]
We have just finished releasing [kube-rbac-proxy v0.4.1](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.4.1). While introducing the hardening of disabling known insecure TLS cipher suites, we discovered, that when TLS certificates are specified all golang default TLS settings are used. This is not the case when certificates are auto-generated on start up as it is the case in standard kube-prometheus. We have already [updated kube-prometheus](https://github.com/coreos/prometheus-operator/pull/2331), and have verified that it is functioning as expected again. We advise to update this component, as TLS connections may be vulnerable.

I'm closing this issue here as it is resolved, but please feel free to comment any questions, should you still have any. Thanks again for your patience and sorry for the inconvenience.

**Comment by yasongxu** [comment]
same problem, I modify the kube-rbac-proxy image（manifests/*.yml） to the new version v0.4.1, but the pod always crashed after run a few time, anything else need to modify except image?

and I remove all --tls-cipher config, the problem fixed, cannot understand....
