### ISSUE TITLE
Thanos sidecar does not get configured properly when using routePrefix

### ISSUE THREAD

**Issue by ephur** [coreos/prometheus-operator#2344]
**What did you do?**
Deployed prometheus with a routePrefix option

**What did you expect to see?**
Thanos query sidecar get updated with the proper prometheus-url argument.

**What did you see instead? Under which circumstances?**
Thanos sidecar did not respect the prometheus route prefix and was thus unable to function as expected

**Comment by metalmatze** [comment]
Whenever running this as a sidecar in Kubernetes I currently do not see a reason to run this with another routePrefix. What are the use cases, I'm just curious! :innocent: 

But as this is supported by Prometheus as `-web.route-prefix` I think we should have this in the sidecar too. :+1:

**Comment by metalmatze** [comment]
Makes sense, thanks for the perfection explanation! :+1: 
Just to double check, changing the prefix on the outside then changes the prefix inside the Pod too, so that Thanos as sidecar can't reach it on 127.0.0.1 either?
We will merge #2345 once the comments have been addressed!

Thanks for looking into this!

**Comment by ephur** [comment]
I see it's already closed, but yes, I can confirm changing the route prefix changes it inside the pod as well. It's inaccessible on / (404) and only accessible via the routePrefix.
