### ISSUE TITLE
Thanos not working with istio 

### ISSUE THREAD

**Issue by AkashDeepSingh265** [coreos/prometheus-operator#2435]
Tried running thanos with promethues operator . We are also using istio in our k8 cluster . The issue i am facing is with istio side car thanos is not working . 

Reason :  the argument generated by prometheus-operator for thanos sidecar is 
--grpc-address=[$(POD_IP)]:10901

But istio forwards traffic to localhost . Due to which istio is not able to forward traffic to thanos side car 

Is there any way to solve this ?

**Comment by brancz** [comment]
We should allow forcing this to the local address just like we allow with Prometheus itself.

**Comment by AkashDeepSingh265** [comment]
Is there any workaround for it ?

**Comment by brancz** [comment]
For now,

**Comment by midnightconman** [comment]
Is this still an issue with thanos `0.4.0`?

**Comment by iainmorris** [comment]
Yes, as far as I can tell, the thanos sidecar is still not functioning in an istio mesh

**Comment by Eslamanwar** [comment]
i facing related issue to that, as i deployed Istio and promethues and thanos
The problem is that when applying Istio Envoyfilter to promethues POD ,thanos-prometheus-thanos-querier cant make query to promethues-server and gives error "rpc error: code = Unknown desc = " address=prometheus-server.metrics.svc.cluster.local.:10901"
