### ISSUE TITLE
Low resource requests and limits for sidecars in prometheus-operator helm chart

### ISSUE THREAD

**Issue by MisterTimn** [coreos/prometheus-operator#2453]
**What did you do?**
Deploy stable/prometheus-operator

**What did you expect to see?**
Alertmanager and prometheus pods coming up without a hitch

**What did you see instead? Under which circumstances?**
Sidecar containers for config-reload and configmap-reload dont start because of low resource requests and limits.
```
 config-reloader:
    Container ID:  docker://15b92a20305388ff7815cc9710ae5fd48b301ecee0c139f97877b70829169176
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      -webhook-url=http://127.0.0.1:9093/monitoring/alertmanager/-/reload
      -volume-dir=/etc/alertmanager/config
    State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
 State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/podc0b26c5c-3c3d-11e9-9063-005056a42579/6fb668d6128ec5ad33145c84b4c8816030f38985a41ec4ffc75c52c9b4b3ef9f/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```
After 61 restarts, the config-reloader and the alertmanager pod come up correctly.

I can't seem to change the resource requests, if i alter the daemonset and restart the pods, it takes the old resource requests.

**Environment**

* Prometheus Operator version:

	quay.io/coreos/prometheus-operator:v0.26.0

* Kubernetes version information:

	v.1.13.3

* Kubernetes cluster kind: 

	self-hosted via kubeadm

**Comment by brancz** [comment]
The prometheus-operator and kube-prometheus helm charts have been migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests or issues about it in this repository. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

Please open an issue on the upstream helm charts repository, as the Prometheus Operator maintainers neither use nor maintain the helm charts.

Thank you for your understanding! :slightly_smiling_face:

Aside from that, your issue has been fixed since v0.29.0 of the Prometheus Operator, which I believe is already part of the latest helm chart release, judging by other issues and comments by users.
