### ISSUE TITLE
Make sidecar resource limits optional

### ISSUE THREAD

**Issue by mxinden** [coreos/prometheus-operator#2472]
Prometheus Operator starts each Prometheus and Alertmanager instance with a config reload sidecar. Resource limits for the side car container can be specified via the `config-reloader-{cpu,memory}` flags. Resource limits can not be disabled which is required by some environments (https://bugzilla.redhat.com/show_bug.cgi?id=1683461).

What do you all think? Would a flag to disable the resource limits on side cars be a valid option?

**Comment by brancz** [comment]
Agreed. When the flag is 0, we should just remove them.

**Comment by s-urbaniak** [comment]
sounds good, yes :+1:

**Comment by MisterTimn** [comment]
Albility to tweak these resource requests and limits would be nice as well. All our sidecars are throttling constantly on our cluster, mainly because low CPU limits are broken.

I've seen PRs adding this functionality, on the CPU request side, to the prometheus sidecars. The same for Alertmanager would be a nice addition.

**Comment by dimm0** [comment]
Also for node-exporter

**Comment by brancz** [comment]
You can already modify node exporter’s limits to your liking. What’s outlined in this issue has been implemented since, hence closing this.
