### ISSUE TITLE
kube-prometheus: monitoring authenticated kubelets

### ISSUE THREAD

**Issue by philips** [coreos/prometheus-operator#250]
**What did you do?**

Deployed kube-prometheus

**What did you expect to see?**

kubelet being scraped

**What did you see instead? Under which circumstances?**

kubelet not being scraped

**Environment**

Tectonic v1.5.5 via Terraform AWS

The problem is that Tectonic has certificate protection on these endpoints; need to figure out how to configure this.

<img width="1432" alt="screen shot 2017-03-30 at 1 25 15 am" src="https://cloud.githubusercontent.com/assets/33544/24480984/dc246398-14e7-11e7-859d-d6ad9fba10fd.png">

**Comment by brancz** [comment]
This is definitely a problem, what kind of a certificate does the kubelet expect? Where would it come from? Is it part of the ServiceAccount certificates mounted?

**Comment by s-urbaniak** [comment]
as far as I see we could reuse the same certs as the api server uses, see https://github.com/coreos/tectonic-installer/blob/3ab7b7d/modules/bootkube/resources/manifests/kube-apiserver.yaml#L42-L43.

They are already available in the tectonic installers as secrets called `kube-apiserver` https://github.com/coreos/tectonic-installer/blob/3ab7b7d/modules/bootkube/resources/manifests/kube-apiserver-secret.yaml.

**Comment by brancz** [comment]
This turns out to be more complex then we thought. So we will have to be able to supply a list of secrets to mount into the Prometheus container. Because we can't change the StatefulSet PodTemplate, the secrets given at point of creation, will be frozen and not reconciled from that point onwards. Targeted for the next release.

**Comment by brancz** [comment]
While this is now possible I'm hesitant to put a default in kube-prometheus just yet, as securing the kubelet in this way is rather rare at this point, and the source of the client certs required are also not standardized. In tectonic this is certainly possible, but not in kube-prometheus.

**Comment by t-trout** [comment]
Could someone please provide an example of how to do this using Promtheus-Operator?  I have been unsuccessful getting access to the ETCD nodes (the endpoints are exposed, but since it requires HTTPS, I need to use the etcd-client.pem and etcd-client-key.pem files generated by kube-AWS when the k8s cluster was generated).

I've tried specifying the tlsConfig for the ETCD service monitor with the caFile, certFile, and keyFile values, but since these are located on the underlying node and not in the Prometheus pod, it can't find them.  I tried to create a volume with a hostPath to the location of these files within my Prometheus.yaml file, but since Prometheus is spun up by Prometheus-Operator, the volume isn't showing up (the volume does not show up when I look at the pods)

I'm thinking that maybe the best approach would be to create a secret with the 3 tlsConfig files (etcd-client.pem, etcd-client-key.pem, ca.pem) but an example showing how to mount the secret in the Prometheus.yaml file and then specifying the secret in my ETCD serviceMonitor would be so wonderfully helpful.  Thanks -
