### ISSUE TITLE
Not able to customize the subject line of alert mail

### ISSUE THREAD

**Issue by k8s-learner** [coreos/prometheus-operator#2580]
I setup the smtp to get the alert emails. But now I am getting 2 environment alerts on 1 mail id.  So I am looking to add the environment name on the subject line.

Suppose this is the subject line :

`[FIRING:1] KubeSchedulerDown (monitoring/pb-k8s-utils-prometheus-op-prometheus critical)`

I am looking for something like this:

`[Systest][FIRING:1] KubeSchedulerDown (monitoring/pb-k8s-utils-prometheus-op-prometheus critical)`

I searched for it. That I can create a template for this, something like this:

```
{{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] | {{ if eq .CommonLabels.job "kube-state-metrics" }}{{ .CommonLabels.alertname }} | {{ .CommonLabels.container }}{{ else }}{{ .CommonLabels.alertname }} | {{ .CommonLabels.instance }}{{ end }}{{ end }}

{{ define "email.default.subject" }}{{ template "__subject" . }}{{ end }}
{{ define "email.cloud.html" }}
```
I don't want much change just add the word. so I don't know where to put it. Could you help me with this.

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
