### ISSUE TITLE
How to send alerts based on the day of the week

### ISSUE THREAD

**Issue by nan008** [coreos/prometheus-operator#2616]
**What did you do?**

    - alert: EmailNot sent
      if: day_of_week() != 0 AND day_of_week() != 6
      annotations:
        message:Not enough email sent
      expr: | ......

**What did you expect?**

Not getting alerts on the weekend, we want to suppress the alert during Sat and Sun. This was (if: day_of_week() != 0 OR day_of_week() != 6) taken from old Prometheus rules set but it is not working on K8S as we got the alerts over the weekend. The alert itself is working as expected

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
