### ISSUE TITLE
I have updated RBAC and NetworkPolicy scripts

### ISSUE THREAD

**Issue by eugene-chow** [coreos/prometheus-operator#262]
While setting up the prometheus operator, I used
1. `contrib/kube-prometheus/hack/cluster-monitoring/self-hosted-deploy.sh`, and
1. RBAC and NetworkPolicy scripts from the `example` folder.

I've updated the config in (2) to work in a self-hosted deployment. I would like to contribute these changes to the repo but where should I put it?

The `example` folder seems to be just for examples (which was why it didn't work ootb), while `contrib/kube-prometheus/hack/cluster-monitoring/` doesn't have a folder for RBAC + NetworkPolicy.

**Comment by brancz** [comment]
RBAC roles have actually recently been added, so that should work from current master, but the `NetworkPolicies` would be more than welcome! I would say we do the same with the `NetworkPolicies` as we did with the `ClusterRole`s and `ClusterRoleBinding`s, and put them in the same folder as the Pods they target. There is no harm in creating network policies for clusters that don't use them as the resource still exists, just doesn't do anything with it, so it would be fine to provision them.

Looking forward to the PR! :slightly_smiling_face:

**Comment by brancz** [comment]
You may also want to talk to @gianrubio who contributed the `NetworkPolicies` currently in the `example/` dir.

**Comment by brancz** [comment]
Also if the current `NetworkPolicies` in the `example/` dir are not covering all aspects, then feel free to add/sync them there as well.

**Comment by eugene-chow** [comment]
Work piled up... Sorry for the delay. After your update to the RBAC roles, both our scripts are similar to the letter :) My contribution would be the NetworkPolicy and RBAC policies for `kube-state-metrics`. My PR is [here](https://github.com/coreos/prometheus-operator/pull/285).

Cheers!

**Comment by brancz** [comment]
Seems like we've resolved all of these with the recently merged PRs. Thanks a lot for all your help @eugene-chow, much appreciated!
