### ISSUE TITLE
Why does Prometheus Operator require access to secrets?

### ISSUE THREAD

**Issue by serain** [coreos/prometheus-operator#2775]
This doc tries to explain Prometheus Operator RBAC in depth, but fails to explain why Prometheus Operator needs all access to all secrets in the cluster.

https://github.com/coreos/prometheus-operator/blob/master/Documentation/rbac.md

**Comment by brancz** [comment]
This is currently required, so that the Prometheus Operator can read and template secrets to build the Prometheus config, and the work being done in https://github.com/coreos/prometheus-operator/pull/2716 requires this as well as features like "additionalScrapeConfigs". There are some thoughts to push this responsibility down to the Prometheus servers in the future, but it's somewhat undecided.

**Comment by serain** [comment]
Thanks

**Comment by pfrydids** [comment]
clusterrole allowing access to all secrets is a big security no no.

Gets highlighted by tools such as Aquasec's Trivy.
