### ISSUE TITLE
How to know a PrometheusRule CRD is actually loaded into Prometheus

### ISSUE THREAD

**Issue by leonliao** [coreos/prometheus-operator#2851]
**What did you do?**
- Create a PrometheusRule Custom Resource(CR)
- The CR is intentionally created with duplicated group name error
- Prometheus has tried to load the 'malformed' CR, but failed(only seen in log of Prometheus), while CR is created successfully

**Did you expect to see some different?**
- There is a way to know whether the CR is loaded by Prometheus successfully programmatically, but not by checking the GUI/log of prometheus.

**Environment**
Nothing special.

* Prometheus Operator version:

 prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.34.0

* Kubernetes version information:

v1.11.0+d4cacc0

* Kubernetes cluster kind:

  OKD
v3.11.0+bd0bee4-337

* Manifests:

* Prometheus Operator Logs:

**Anything else we need to know?**:

**Comment by brancz** [comment]
There is no such possibility today, largely because a PrometheusRule can in theory be loaded by multiple Prometheus servers at once, which one would then be assigned, or should all show up? Plus to actually know whether it was loaded we need to communicate directly to the Prometheus server, which is not something that the Prometheus Operator does today, but would be desirable for other features so we might end up doing that at some point.

**Comment by leonliao** [comment]
Thanks.

I figured out that it is possible to do syntax check using the [Admission Web Hook]?(https://github.com/coreos/prometheus-operator/blob/f1392d5430147b033d01ebb6a67ded18d2f2e6fc/pkg/admission/admission.go)

There is zero documentation for how to configure, or maybe I failed to locate the docs.
