### ISSUE TITLE
Question: how to set custom prometheus-flags?

### ISSUE THREAD

**Issue by robrsprd** [coreos/prometheus-operator#306]
I try to keep the question short :)

Is there a way to set the flags prometheus is  started with?
Would it work if I push a custom container to my registry and use it as baseimage for my "Prometheus"? And will the operator override any of these custom flags? 

Thanks in advance

**Comment by brancz** [comment]
The point of the Prometheus Operator is to abstract away the configuration as much as possible and leave it to the Prometheus Operator. What exactly would you be looking for in terms of custom flags? If it's a reasonable configuration it is probably rather a missing feature.

The reasoning behind this is that we can ensure consistent configuration for Prometheus instances, based on experiences we've made as Prometheus maintainers, contributors and users. :slightly_smiling_face:

As soon as you start using a non standard image (either from the [canonical image repo](https://quay.io/repository/prometheus/prometheus?tag=latest&tab=tags) or a mirror of it), we can only support your usage in a limited way.

**Comment by robrsprd** [comment]
I really appreciate the operator's ease of use and the very complete out-of-the-box-experience for k8s-monitoring, BUT: as our current k8s-landscape consists of "more or less many", "more or less small" clusters (which are again federated) it feels kinda greedy in terms of memory-usage if you sum everything up - so my idea was to tweak it a bit by playing around with some flags. 

After some research i realized, that a custom image would most likely dont do the work, as all it's CMDs would be discarded and set by the k8s-ressource:

Args:
      -storage.local.retention=24h (is the only one which can be configured)
      -storage.local.memory-chunks=81920
      -storage.local.max-chunks-to-persist=40960
      -storage.local.num-fingerprint-mutexes=4096
      -storage.local.path=/var/prometheus/data
      -config.file=/etc/prometheus/config/prometheus.yaml 

I fully understand the approach to offer a best-practice-design. But not offering the option to change some defaults is very limiting in my particular case. So, yes, I would personally call it a missing feature :) But myabe, if nobody ever requested it, it's just me :D

**Comment by brancz** [comment]
Those flags are specifically what we don't want users to manually touch as it is the hard part about operating Prometheus, plus there are significant changes due to the Prometheus v1.6 release that are [reflected in the code](https://github.com/coreos/prometheus-operator/pull/295), but a hard specification would be too erroneous as for example these flags are completely disappearing in Prometheus 2.0, so allowing to customize them allows the result to generate a non working Prometheus configuration.

Note: the values of those flags are calculated depending on the resource requests one specifies in the Prometheus object.

So what I'm saying is we might allow further customization to those flags as long as it's not the raw access, but in form of an abstraction that makes sense and we can continue to support for future releases of Prometheus, that abstraction so far has been the targeted memory usage, which we can estimate for by calculating the flag values for it.

**Comment by brancz** [comment]
As mentioned, the direct access to the storage flags are a non goal for the Prometheus Operator, if we can find an abstraction that makes sense and allows more control that would be fine, but needs to be translatable to any storage implementation, therefore memory request was our currently chosen abstraction, the chosen ratios can be argued with. Closing here.
