### ISSUE TITLE
Bug on Time based Functions, PromQL

### ISSUE THREAD

**Issue by chadi3** [coreos/prometheus-operator#3063]
**What happened?**
Cannot merge queries for time based functions

To Filter from 1:00 to 18:30, used the below query

`(vector(1) and ((hour() >= 01) and  ((hour() <= 18) and (minute() <= 30 )) )) or (vector(0))` 

This gave result as,
![image](https://user-images.githubusercontent.com/30234760/75909044-4e86e480-5e71-11ea-9cd2-6a271f10fff1.png)

**Did you expect to see something different?**

The query should be giving `vector 1` from 1:00 to 18:30, Instead Filters time for every 30 mins,

As an alternative tried the below query which doesn`t help,

`(vector(1) and ((hour() >= 01) and  (hour() <= 18.5) )) or (vector(0))` 

**Environment**

Kubernetes Version: 1.11.6
Prometheus Version: 2.4.3

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
