### ISSUE TITLE
how to get resource metrics like kube_pod_container_resource_requests_memory_bytes

### ISSUE THREAD

**Issue by ryandawsonuk** [coreos/prometheus-operator#3226]
I've previously been working with the prometheus helm chart and was used to seeing metrics for resources [like kube_pod_container_resource_requests_memory_bytes](https://www.replex.io/blog/kubernetes-in-production-the-ultimate-guide-to-monitoring-resource-metrics-with-grafana). I'm using this operator on OpenShift withe CSV and creating a ServiceMonitor and PodMonitor for my app. I see the metrics that the app exposes on a /metrics endpoint. But I don't see how to get kubernetes pod resource usage metrics.

**Comment by lilic** [comment]
More of a openshift specific question rather than this operator, but since I work on this there can answer it :)
- In openshift this operator is already installed by default for both user and cluster workloads.
- those metrics do not come from your app or this operator but from kube-state-metrics (they will be in openshift depending on the version of openshift your are using and can query them for those pods already without anything else installed)
- you do not need this operator to see metrics about your app in openshift, you can just enable user workload monitoring from 4.3 onwards.

Let me know if something doesn't make sense.

**Comment by ryandawsonuk** [comment]
Ok so in order to get resources I should [enable Monitoring](https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services) and not use the community prometheus operator from operatorhub. Yes that's clear.

I'm actually hoping to create an operator that uses other operators including prometheus. Will need a prometheus to use as a dependency. Am currently a bit unsure about using the built-in monitoring because it's in tech preview and has to be enabled. If you know anything about that or know someone I can speak to any help would be appreciated. Otherwise thanks for answering the resource monitoring question.

**Comment by lilic** [comment]
> Ok so in order to get resources I should enable Monitoring and not use the community prometheus operator from operatorhub. Yes that's clear.

you can use just the default installed prometheus in the cluster and query there, the kube-state-metrics metric you are talking about are already on the cluster. So for that metric no need for user workload monitoring, for gathering metrics about user apps you should enable monitoring yes.

>If you know anything about that or know someone I can speak to any help would be appreciated.
 
Sure feel free to reach out on k8s slack, we have openshift-devs or openshift-users we can discuss your use case, as it's outside of this operator. But I do not think you need this operator as a deps for that, but I don't know what you are building.

**Comment by ryandawsonuk** [comment]
Ok I see what you mean now. Yes it is there, it's just in a different prometheus instance from the one I'm looking at.
