### ISSUE TITLE
Promql - Need to create alert on pod restart on the most recent pod created.

### ISSUE THREAD

**Issue by nehagupta84** [coreos/prometheus-operator#3228]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
