### ISSUE TITLE
Using Blackbox exporter probe_http_status_code is 200 But probe_success is 0 from Prometheus

### ISSUE THREAD

**Issue by satyendranit** [coreos/prometheus-operator#3254]
I am using kubernetes setup, where I am using blackbox exporter to probe external URLs from Prometheus. But I am surprised with two different things like my probe_http_status_code response is 200 but my probe_success response is 0. how can a probe_http_status_code response be 200 while probe is failing.

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/blackbox exporter.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by evalizhangli** [comment]
> 

I met the same problem. how do you solve this?
