### ISSUE TITLE
Prometheus has failed to evaluate 20 rules in the last 5m

### ISSUE THREAD

**Issue by lianfulei** [coreos/prometheus-operator#3344]
rule_group=/etc/prometheus/rules/prometheus-po-prometheus-operator-prometheus-rulefiles-0/monitoring-po-prometheus-operator-kubernetes-system-kubelet.yaml;kubernetes-system-kubelet
rule_group=/etc/prometheus/rules/prometheus-po-prometheus-operator-prometheus-rulefiles-0/monitoring-po-prometheus-operator-kubelet.rules.yaml;kubelet.rules

Prometheus monitoring/prometheus-po-prometheus-operator-prometheus-0 has failed to evaluate 20 rules in the last 5m
Prometheus is failing rule evaluations
why?

**Comment by lianfulei** [comment]
i have solve it

**Comment by FL3SH** [comment]
Can you share how you solved it?

**Comment by lianfulei** [comment]
rules must create through prometheusrule

**Comment by lianfulei** [comment]
@FL3SH rules must create through prometheusrule

**Comment by FL3SH** [comment]
Can you explain it? I am using a promthues-operator to create rules.

**Comment by lianfulei** [comment]
create yaml files
kind: prometheusrule
@FL3SH

**Comment by byakku** [comment]
In case someone will be looking for the error here - I had to redeploy CRDs, somehow I had totally different resources and that's why it was firing the same error.

**Comment by mshivanna** [comment]
I had to delete duplicate svcs

**Comment by jacksondaw** [comment]
For anyone else running into this, this issue pointed me in the right direction https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/392

The duplicate services are in the kube-system namespace. 

After upgrading to 14.x on one cluster the services were:

kubelet 
prometheus-operator-kube-p-kubelet 

I resolved the issue by deleting the kubelet svc. 

On another cluster the duplicate services were

prometheus-community-kube-kubelet
prometheus-operator-kube-p-kubelet 

Deleting prometheus-community-kube-kubelet resolved the issue.

**Comment by mcs** [comment]
Because Google always sends me here although the useful hint on how to locate the exact rule causing the error: just open the Prometheus UI and switch to `Status --> Rules`. 
![image](https://github.com/prometheus-operator/prometheus-operator/assets/33131/448e3119-2ddd-481f-8e25-f48ed63e38f9)
The violating rule should be rendered with a good visible red background so one can scroll fast through the rules:
![image](https://github.com/prometheus-operator/prometheus-operator/assets/33131/84487848-c3cf-4e27-ad3c-4dca21a3d563)
