### ISSUE TITLE
Update helm chart to include all features of contrib/kube-prometheus for cluster monitoring

### ISSUE THREAD

**Issue by ryanwalls** [coreos/prometheus-operator#373]
There is a helm chart that @mgoodness started in the `helm` directory.  Ideally, it would have all the features of the `contrib/kube-prometheus` scripts.  i.e.  It would be great to have a single helm chart that installed a full cluster monitoring solution.  

From what I can tell, the chart currently only installs the prometheus operator.  

This would help with issues like #363 where people want to run prometheus operator on something other than k8s 1.6 as we could have versioned helm charts that correlate to k8s versions.

**Comment by mgoodness** [comment]
#277 will provide this, along with a few other stand-alone charts I'm working on now. I promise it won't be much longer

**Comment by brancz** [comment]
Yeah @mgoodness is already working on this, so if he needs any help then I'll let him coordinate.

@mgoodness let the community know if/how they can help, the more people working on it the better :wink:

**Comment by tsloughter** [comment]
Since #277 was merged does this mean this issue is "resolved"?

One thing I noticed when looking through the helm charts (currently using the kube-prometheus scripts and want to switch to helm since everything else we do is through helm charts) I noticed that the `kube-prometheus` chart does not have `prometheus-operator` as a requirement.

Does that mean I would want to install both of them separately to get the same result as the deploy script from `contrib/kube-prometheus`?

**Comment by mgoodness** [comment]
Yes, you need to install the `prometheus-operator` chart first. That's the only way to guarantee that the ThirdPartyResources types exist before the `kube-prometheus` chart instantiates them.

We'll continue to refine the charts, but you're right that this issue can be closed.
