### ISSUE TITLE
Multi-Apiserver -> Target apiserver flaky

### ISSUE THREAD

**Issue by strowi** [coreos/prometheus-operator#479]
Hi,

i deployed a 3-Master kubernetes with matchbox. Taking a look at the targets, prometheus shows only a single api-endpoint that seems very flaky, switching the ip between the pods, and changing status between unknown and up..

Is there any solution to this?

**Comment by galexrt** [comment]
The solution to this is to add a flag to all Kubernetes apiserver called `--apiserver-count=X` where `X` is the count of the apiservers. Then the endpoint is created correctly with all apiservers in them and prometheus should discover them correctly.

**Comment by strowi** [comment]
thx, it works;)

**Comment by neuromantik33** [comment]
Hi I'm facing a similar issue on GKE reported by me described [here (gke issuetracker)](https://issuetracker.google.com/issues/109894256) however I'm unable to modify the apiserver as it is managed elsewhere. Is there a possible workaround which would allow me to continue monitoring the k8s apiserver?

**Comment by brancz** [comment]
You can create an artificial service and Endpoints object where you manage the IPs manually.

As an update the correct solution is not the apiserver count anymore, as this turned out to have problems as well. The recommended way is to use the lease Endpoints reconciler, which I believe in 1.11 will be default.

 Evertheless Google should enable this flag for all 1.9+ clusters (which is when the lease Endpoints reconciler was introduced).

**Comment by neuromantik33** [comment]
Ok thanks, I figured I would create my own synthetic service/endpoint, thanks for the quick reply! :)
