### ISSUE TITLE
e2e test operator container image

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#48]
It seems like the default process should be to test the operator image that would result from the current repository HEAD. Currently it may be confusing to run `make e2e` and have it being tested as the `:latest` tagged image by default.

@brancz

**Comment by brancz** [comment]
yep was thinking of that as well, I'd suggest we 1) allow specifying the "default" being used in tests as a flag 2) build the container image in the makefile setting the tag to current HEAD sha 3) use that tag in the "default" tag flag.

This highly assumes using minikube though, otherwise we need a "test" repository where we upload the image to be used in the test, and then we're not even completely use if there isn't a caching problem.

What are your thoughts?

**Comment by fabxc** [comment]
Or an option to ran the operator locally outside of the cluster. Though that's of course reducing the end-to-end-ness to a degree.

I think for getting it work nicely locally with minikube is good enough and doing it as you said with the current HEAD sha.
