### ISSUE TITLE
node-exporter could not export all mountpoints  

### ISSUE THREAD

**Issue by wkjun** [coreos/prometheus-operator#569]
node-exporter in this yaml  :

prometheus-operator/contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml

volumes and mountpoints doesn't content : 

   "/:/rootfs:ro" 

not like node-exporter:
https://github.com/prometheus/node_exporter

why not add the to it?

**Comment by brancz** [comment]
there are a few things around the node-exporter daemonset we have currently that can be improved, if this change works in your setup, feel free to contribute it :slightly_smiling_face:

**Comment by weiwei04** [comment]
Since kubernetes not support mount propagation, `/:/rootfs:ro` will cause some mount/unmount issues on host machine(for example if you use networked block device like ceph rbd/aws ebs etc), see https://github.com/prometheus/node_exporter/pull/660

after this pr https://github.com/kubernetes/kubernetes/pull/46444 merged, I think we can consider run node_exporter with `/:/rootfs:ro,rslave`.

**Comment by brancz** [comment]
Mount propagation is now on by default in Kubernetes 1.10, so I’m closing this.

**Comment by kashwinbhat** [comment]
Hi, can someone give more information on what is the potential issue that is observed when the root ('/') mount is not used.

I tried using both the cases with / hostpath and without it the node-exporter metrics was exactly similar, If any can give the details of the issue of not having / as hostpath that will help me.
 
https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/node-exporter-daemonset.yaml#:~:text=name%3A%20sys-,-%20hostPath%3A,name%3A%20root,-updateStrategy%3A
