### ISSUE TITLE
Prometheus 2.0 Alert format documentation

### ISSUE THREAD

**Issue by wleese** [coreos/prometheus-operator#593]
**What did you do?**
Use Prometheus 2.0.0 beta 2 with kube-prometheus.

**What did you expect to see?**
Alerts defined in the UI of prometheus

**What did you see instead? Under which circumstances?**
Nothin'

It's currently unclear how / if it's possible to create a configmap with a 2.0 style Alert definition, and the old style isn't migrated in any way.

**Comment by brancz** [comment]
This is currently expected, as the kube-prometheus manifests are only provided as is and are always specific to the latest stable version of Prometheus.

`promtool`, a small utility shipped with every Prometheus release is able to convert rules from old to new Prometheus alerting rule syntax. You should be able to just run it over all alerting rule definitions, run the manifest generation scripts and apply the `ConfigMap`s, and you should be good to go! :slightly_smiling_face: 

Let me know how it goes, but as this is currently not something we're supporting I'll close this issue here, but feel free to ask further questions if you have any.

**Comment by wleese** [comment]
Many thanks.

What I did was run:
```
promtool update rules assets/prometheus/rules/*
```
and update hack/scripts/generate-rules-configmap.sh
```
--- a/hack/scripts/generate-rules-configmap.sh
+++ b/hack/scripts/generate-rules-configmap.sh
@@ -11,8 +11,8 @@ metadata:
 data:
 EOF
 
-for f in assets/prometheus/rules/*.rules
+for f in assets/prometheus/rules/*.rules.yml
 do
-  echo "  $(basename $f): |+"
+  echo "  $(basename $f | sed s/\.yml//): |+"
   cat $f | sed "s/^/    /g"
 done
```

**Comment by brancz** [comment]
Awesome, thanks for sharing! That will be useful once we migrate! :slightly_smiling_face:
