### ISSUE TITLE
[FIRING:1] K8SApiserverDown (critical)

### ISSUE THREAD

**Issue by kubebc** [coreos/prometheus-operator#724]
on our two Tectonic 1.7.5 stacks on AWS, I get "[FIRING:1] K8SApiserverDown (critical)" everyday. But our micro-services are running fine.

Any idea what's the reason for that? If there're false alarms, can I just turn off the warning? Thanks!

fyi, 
1 alert for alertname=K8SApiserverDown 
[1] Firing 
Labels
alertname = K8SApiserverDown
severity = critical
Annotations
description = No API servers are reachable or all have disappeared from service discovery
Source

**Comment by brancz** [comment]
This is unfortunately a problem with HA Kubernetes apiserver implementation itself. The way Prometheus discovers targets in Kubernetes is through `Endpoints` objects. When there are multiple highly available apiservers, they keep overwriting each other causing Prometheus to not be able to scrape the apiservers. This has been fixed upstream, however, will only land in the 1.9 release. For the time being I recommend to silence the alert in the Alertmanager.

**Comment by kubebc** [comment]
Thanks a lot! brancz :)
I'm new to prometheus-operator, how to silence this series of alerts once for all? or do you prefer to recommend us to silence each alerts day by day?

**Comment by brancz** [comment]
The Tectonic Console has a link to the Alertmanager UI under the "Troubleshooting" tab. The link is called "Prometheus Alerts". You may need to login a second time. Then you click on "New Silence" in the top right corner. Then you create the matcher to be `alertname = K8SApiserverDown`, then you should not be alerted about this issue anymore. I would recommend silencing it until you have upgraded to the Tectonic release that ships with Kubernetes 1.8.x, as we have refined the alert to hopefully not fire as often, but probably it will still fire once in a while sadly due to the above mentioned issue. Ultimately if it still fires after the next upgrade I recommend silencing it until the release that ships with Kubernetes 1.9.x. Kubernetes 1.9.x ships december/january and the Tectonic release should follow soon after that.

Generally if an alert is so noisy that you start ignoring it, it should be silenced (or removed if you have control over that, which you don't for the Tectonic Monitoring alerts, as they are fully managed by us), and if there is a noisy alert that shouldn't be and it ships with Tectonic then we should figure out how to improve it so it gets you the most value. tl;dr if it's noisy and an alert that we provide create a ticket for it, so you've done it all correct :slightly_smiling_face: .

**Comment by KeithTt** [comment]
Also find this problem in the webui of prometheus:

![image](https://user-images.githubusercontent.com/15189954/34513666-51561e7a-f0a4-11e7-8590-d842a58dd48c.png)

**Comment by brancz** [comment]
Starting with Kubernetes 1.9 this is fixed with the lease endpoint reconciler. Before that this is a known issue in Kubernetes causing this. With Kubernetes 1.9 simply pass:

```
--endpoint-reconciler-type=lease
```

To your apiserver and the problem will disappear :slightly_smiling_face: .
