### ISSUE TITLE
Support for configuring targets outside kubernetes cluster

### ISSUE THREAD

**Issue by kornface13** [coreos/prometheus-operator#775]
**What did you do?**
I have Prometheus operator setup and monitoring things in my kubernetes cluster.  I'd like to add some targets that are outside the cluster.  The server is running node exporter.  

if I weren't using the operator, I could simply add the following to my prometheus config:
  - job_name: "randomserver01"
    scrape_interval: "10s"
    target_groups:
    - targets: ['10.248.0.11:9100']

However it doesn't appear possible to edit the config, and I can't find documentation showing support for this or what the yaml file would look like.  Is this possible, or should this be a feature request?

**Comment by brancz** [comment]
There are two strategies you can go with, the first being that you manually maintain an `Endpoints` object and a respective `Service` and manually maintain the IPs for those. Then you can use the `ServiceMonitor` pattern as with anything else.

Otherwise if you want to use any of the other target discovery mechanisms available in Prometheus, you can go with a fully [custom configuration](https://github.com/coreos/prometheus-operator/blob/master/Documentation/custom-configuration.md).

**Comment by brancz** [comment]
We recently released the `additionalScrapeConfigs` feature, where you can specify arbitrary scrape configs known from the prometheus configuration, while making use of all the other features of the Prometheus Operator.

Closing here as there are now options to do what you requested, but feel free to re-open or open a new issue should you have any problems with this feature!
