### ISSUE TITLE
share influxdb with heapster

### ISSUE THREAD

**Issue by moos3** [coreos/prometheus-operator#856]
Is there a way to share the same influxdb as say heapster? So that all the data is collected in the same sink? this would help with tools like kapacitor and cluster autoscaler. 

**Environment**

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:12:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: Kops

**Comment by brancz** [comment]
Prometheus has it's own time-series database, you would want to use the tooling around the Prometheus ecosystem, also note that heapster is in the process of being deprecated.

This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
