### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by murphyzh** [coreos/prometheus-operator#900]
![image](https://user-images.githubusercontent.com/13235265/35040336-aca5f3aa-fbbb-11e7-9871-de58dc81ee48.png)
is memory leak? the memory of pod permetheus-k8s is increasing?
how to solve this problem? thx

**Comment by brancz** [comment]
That's just the go garbage collector, which starts collecting garbage when garbage size == heap size. This is expected. You should however increase your memory request, since ~1Gb seems to be around your base line.

I'm closing this here, as it's a non issue, but feel free to ask if you have any further questions.
