### ISSUE TITLE
How to get POD stats by executing http_requests_total

### ISSUE THREAD

**Issue by AnkitVaidya01** [coreos/prometheus-operator#913]
What did you do?
I deployed prometheus-operator (kube-prometheus) and then deployed my application pods and services. Now on the prometheus ui, when I executed 'http_requests_total'

What did you expect to see?
When I execute 'http_requests_total', it should return http requests stats of my deployed pods.

What did you see instead? Under which circumstances?
It only returned data of monitoring namespaces resources, not any stats for my deployed pods.

@brancz @grobie @tomwilkie @matthiasr @jimmidyson@fabxc @kubernetes/sig-instrumentation

**Comment by brancz** [comment]
@AnkitVaidya01 first step is that your applications actually expose metrics. Then Prometheus needs to discover your targets and collect the metrics. Once you collect those metrics you can visualize them.

There is an example of this here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/examples/example-app

You can find an example application exposing metrics here: https://github.com/brancz/prometheus-example-app

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by shindanim** [comment]
For the future viewer's information, the example seems to be moved to https://github.com/coreos/kube-prometheus/tree/master/examples/example-app
