### ISSUE TITLE
How to setup Slack alerts for Alertmanager?

### ISSUE THREAD

**Issue by ScottBrenner** [coreos/prometheus-operator#927]
Having trouble getting alerts from Alertmanager to send to Slack, could someone please provide a walk-through?

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
